### ISSUE TITLE
Any idea how to get localhost plugins work in Safari / WebKit based browsers?

### ISSUE THREAD

**Issue by notyourneighborson** [ai-collection/ai-collection#109]
Any idea how to get localhost plugins work in Safari / WebKit based browsers?

_Originally posted by @tddschn in https://github.com/openai/plugins-quickstart/issues/11#issuecomment-1555436688_

**Comment by blueberrychopsticks** [comment]
What did you do to fix this? It works in Chrome but not Safari

**Comment by 360macky** [comment]
Doesn't work in Safari
