### ISSUE TITLE
Obsolete link, what the process like? 

### ISSUE THREAD

**Issue by souhailmerroun** [ai-collection/ai-collection#143]
Hello,

This link "aidev.codes" seems to be in migration for now.

<img width="870" alt="image" src="https://github.com/ai-collection/ai-collection/assets/8895242/d6705e87-fb6c-406c-9c5b-3e2445928d8d">

**Comment by kerbelp** [comment]
I've removed unreachable websites. you can always submit websites with new urls to www.thataicollection.com/submit or just email me: pavel@ai-collection.org
