### ISSUE TITLE
Add Tabula to Sales and Marketing

### ISSUE THREAD

**Issue by Anastasia-Antonova-retable** [ai-collection/ai-collection#149]
Tabula.io - Your personal GPT-powered data assistant

From content generation in bulk to dashboard creation, Tabula will serve as your own marketing analyst. Automate performance reporting, enrich customer data, map customer base, and build personalized approaches to any of your customer segments

More details: https://www.tabula.io/solution/marketing-analytics

**Comment by kerbelp** [comment]
Hi, 
You can submit your AI application using our self serve flow: www.thataicollection.com/submit
