### ISSUE TITLE
【网站自荐】AI好物——根据一句话推荐商品

### ISSUE THREAD

**Issue by zhugezifang** [ai-collection/ai-collection#170]
产品地址：https://www.ai-code.online/

介绍：AI好物是一个好物推荐网站，当你有需求又不知道买什么的时候，可以根据输入内容给你推荐商品

AI好物诞生的背景：https://www.ai-code.online/story

**Comment by kerbelp** [comment]
Hi, please submit your app using: www.thataicollection.com/submit
