### ISSUE TITLE
Check if has API

### ISSUE THREAD

**Issue by NetanelRotem** [ai-collection/ai-collection#30]
thank you so much for the list!, that will be great to have a check box, if the service has API. and thank you again!

**Comment by kerbelp** [comment]
Thanks, I think that it's a good idea.
Do you have an example of one of these tools that has a public api (except of chatGPT of course)?
I want to see if there is a common way that the websites refer to the docs?

**Comment by kerbelp** [comment]
I'll add it to the website.
Will not add it to the GitHub repo at this time.
